---
kind: pipeline
type: docker
name: default

steps:
- name: install, build doc run scripts
  image: python:3.7
  commands:
  - git fetch --tags 
  - pip install Cython sphinx sphinx_rtd_theme
  - python setup.py install
  - cd doc
  - make html
  - cd ../scripts
  - python arcs.py
  - python simple_shapes.py
  - python roundedlines.py
  - python polygon2D.py
  - python polygon2D_2.py
  - python extrusion.py
  - python demo2D.py
  - python casing.py
  - python sweep.py

- name: develop
  image: python:3.7
  commands:
  - pip install Cython
  - python setup.py develop

- name: sdist, bdist, wheel
  image: python:3.7
  commands:
  - pip install Cython wheel
  - python setup.py sdist
  - python setup.py bdist
  - python setup.py bdist_wheel

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password
