---
kind: pipeline
type: docker
name: default

steps:
- name: install, build doc run scripts
  image: python:3.7
  commands:
  - git fetch --tags 
  - pip install Cython sphinx sphinx_rtd_theme
  - python setup.py install
  - cd doc
  - make html
  - cd ../scripts
  - python arcs2D.py
  - python arcs3D.py
  - python simple_shapes.py
  - python roundedlines.py
  - python polygon2D.py
  - python polygon2D_2.py
  - python extrusion.py
  - python demo2D.py
  - python casing.py
  - python sweep.py
  - python revolved_profile.py
  - cd distance
  - python arc3D_arc3D.py
  - python arc3D_ls3D.py
  - python cyl_cyl.py
  - python cyl_pf.py
  - python ls3D_ls3D.py
  - python sweep_sweep.py
  - python tore_cyl.py
  - python tore_pf.py
  - python tore_tore.py

- name: develop
  image: python:3.7
  commands:
  - pip install Cython
  - python setup.py develop

- name: sdist, bdist, wheel
  image: python:3.7
  commands:
  - pip install Cython wheel
  - python setup.py sdist
  - python setup.py bdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: notify by email
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
