---
kind: pipeline
type: docker
name: default

steps:
- name: install, build doc run scripts
  image: python:3.8
  commands:
  - git fetch --tags 
  - pip install Cython sphinx sphinx_rtd_theme
  - python setup.py install
  - cd doc
  - make html
  - cd ../scripts
  - python ci_scripts.py

- name: develop
  image: python:3.8
  commands:
  - pip install Cython
  - python setup.py develop

- name: sdist, bdist, wheel
  image: python:3.8
  commands:
  - pip install Cython wheel
  - python setup.py sdist
  - python setup.py bdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password



- name: notify by email
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
