---
kind: pipeline
type: docker
name: default

steps:
- name: check code complexity
  image: python:3.9
  commands:
  - pip install radon pylint
  - ./code_quality.sh
  - python code_pylint.py

- name: check pep8 formatting
  image: python:3.9
  commands:
    - git fetch --tags
    - pip3 install -U pip autopep8
    - bash code_pep8.sh

- name: install, build doc run scripts
  image: python:3.8
  commands:
  - git fetch --tags
  - pip install Cython sphinx sphinx_rtd_theme coverage
  - python setup.py install
  - cd doc
  - make html
  - cd ../scripts
  - coverage run --source volmdlr ci_scripts.py
  - coverage json
  - coverage report
  - python coverage.py

- name: generate sdist
  image: python:3.8
  commands:
  - git fetch --tags
  - pip install Cython
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_master
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/volmdlr/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password


- name: notify by email
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
      from_secret: email_password
    from: technical@dessia.tech
