---
kind: pipeline
type: docker
name: default

steps:
- name: merge master on testing
  image: alpine/git
  when:
    event: push
    branch: master
  failure: ignore
  commands:
  - cd /tmp
  - git clone $DRONE_GIT_HTTP_URL
  - cd volmdlr
  - git checkout master
  - git fetch origin testing
  - git checkout testing
  - git merge master
  - git push

- name: merge testing on dev
  image: alpine/git
  when:
    event: push
    branch: testing
  failure: ignore
  commands:
  - cd /tmp
  - git clone $DRONE_GIT_HTTP_URL
  - cd volmdlr
  - git checkout testing
  - git fetch origin dev
  - git checkout dev
  - git merge testing
  - git push

- name: check code complexity
  image: python:3.9
  commands:
  - pip install radon pylint pydocstyle pre-commit shellcheck-py cython-lint
  - ./code_quality.sh
  - python code_pylint.py
  - python code_pydocstyle.py
  - pre-commit run -a

  volumes:
    # Mount pip cache from host
    - name: cache
      path: /root/.cache


- name: check pep8 formatting
  image: python:3.9
  commands:
    - git fetch --tags
    - pip3 install -U pip autopep8==2.0.0
    - bash code_pep8.sh

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip

- name: check changelog update
  image: python:3.8
  when:
    event: pull_request
  commands:
    - bash code_changelog.sh

- name: install, build doc run scripts and tutorials
  image: python:3.8
  commands:
  - git fetch --tags
  - pip install Cython sphinx sphinx_rtd_theme coverage nbformat nbconvert
  - python setup.py install
  - cd doc
  - make html
  - cd ../tests
  - coverage run --source volmdlr -m unittest discover -v
  - cd ../scripts
  - coverage run --source volmdlr ci_scripts.py
  - cd ../tutorials
  - coverage run --source volmdlr ci_tutorials.py
  - cd ..
  - coverage combine scripts/.coverage tests/.coverage tutorials/.coverage
  - coverage json
  - coverage report
  - python coverage.py

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip

- name: generate sdist
  image: python:3.8
  commands:
  - git fetch --tags
  - pip install Cython
  - python setup.py sdist

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip


- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_master
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/volmdlr/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password


- name: notify by email
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
      from_secret: email_password
    from: technical@dessia.tech

volumes:
  - name: pip_cache
    host:
      path: /tmp/cache/drone/pip
  - name: cache
    host:
      path: /tmp/cache/drone
