---
kind: pipeline
type: docker
name: default

steps:
- name: install, build doc run scripts
  image: python:3.7
  commands:
  - git fetch --tags 
  - python setup.py install
  - pip install sphinx sphinx_rtd_theme
  - cd doc
  - make html
  - cd ../scripts
  - python arcs.py
  - python simple_shapes.py
  - python roundedlines.py
  - python polygon2D.py
  - python polygon2D_2.py
  - python extrusion.py
  - python demo2D.py
  - python casing.py
  - python sweep.py

- name: develop
  image: python:3.7
  commands:
  - pip install Cython
  - python setup.py develop

- name: sdist
  image: python:3.7
  commands:
  - python setup.py sdist --formats=gztar,zip

