clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

pipeline:
  merge-master-testing:
    image: alpine/git
    when:
      event: push
      branch: master
    commands:
    - cd /tmp
    - git clone $DRONE_GIT_HTTP_URL
    - cd volmdlr
    - git checkout master
    - git fetch origin testing
    - git checkout testing
    - git merge master
    - git push

  merge-testing-dev:
    image: alpine/git
    when:
      event: push
      branch: testing
    commands:
    - cd /tmp
    - git clone $DRONE_GIT_HTTP_URL
    - cd volmdlr
    - git checkout testing
    - git fetch origin dev
    - git checkout dev
    - git merge testing
    - git push

  email-notify:
    when:
      event: push
      branch:
        - master
        - dev
      status:
      - failure
    image: drillster/drone-email
    settings:
      host: mail.dessia.tech
      username: technical@dessia.tech
      password:
        from_secret: email_password
      from: technical@dessia.tech

  check-code-complexity:
    image: dessia/python-ci:3.9
    commands:
      - git fetch --tags
      - pip install Cython
      - pip install 'numpy<1.24.0'
      - python setup.py build_ext --inplace
      - python setup.py install
      - pip install pylint==2.17.3 pydocstyle==6.3.0 pre-commit shellcheck-py cython-lint pyenchant==3.2.2
      - python code_pylint.py
      - python code_pydocstyle.py
      - pre-commit run -a


  check-pep8-formatting:
    image: python:3.9
    commands:
      - git fetch --tags
      - pip3 install -U pip autopep8==2.0.0
      - bash code_pep8.sh

  check-changelog-update:
    image: python:3.9
    when:
      event: pull_request
    commands:
      - bash code_changelog.sh

  install-doc-coverage:
    image: python:3.9
    commands:
      - pip install Cython sphinx sphinx_rtd_theme coverage nbformat nbconvert 'numpy<1.24.0'
      - python setup.py build_ext --inplace
      - python setup.py install
      - cd doc
      - make html
      - cd ../tests
      - coverage run --rcfile=../.coveragerc --data-file=../.coverage --source volmdlr -m unittest discover -v
      - cd ../scripts  
      - coverage run --rcfile=../.coveragerc --data-file=../.coverage --source volmdlr -a ci_scripts.py
      - cd ../tutorials
      - coverage run --rcfile=../.coveragerc --data-file=../.coverage --source volmdlr -a ci_tutorials.py
      - cd ..
      - coverage json
      - coverage report
      - coverage html
      - python coverage.py
    volumes:
      - /tmp/cache/drone/pip/:/root/.cache/pip/

  generate-sdist:
    image: python:3.9
    commands:
      - git fetch --tags
      - pip install Cython
      - pip install 'numpy<1.24.0'
      - python setup.py sdist


  upload-coverage:
    image: appleboy/drone-scp
    when:
      event: push
    failure: ignore
    settings:
      host: magenta.dessia.tech
      target: /var/www/cdn/volmdlr/coverage/${DRONE_BRANCH}
      source: htmlcov/*
      strip_components: 1
      username: drone
      password:
        from_secret: ssh_drone_password



