name: Test install

# Build on every branch push, tag push, and pull request change:
on: [push]

jobs:
  build_wheels:
    name: Build wheels on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: 3.9

      - name: Install
        run: |
          pip install .

